// src/components/ListItemShow.tsx
import { css } from '@styled-system/css'

type Show = {
  summary: string
  start: string
  end: string
  description: string
  url: {
    val: string
  }
  formatted_start: string
}

export function ListItemShow({
  summary,
  start,
  end,
  description,
  url,
  formatted_start,
}: Show) {
  return (
    <div className="list_item-show">
      <span className={css({ textStyle: 'h5' })}>
        {url && url.val ? (
          <a href={url.val}>
            {formatted_start} @ {summary}
          </a>
        ) : (
          <span>
            {formatted_start} @ {summary}
          </span>
        )}
      </span>
      <p>{description}</p>
    </div>
  )
}

// src/routes/shows/ListItemShow.svelte
<script lang="ts">
	import { css } from 'styled-system/css';
	import type { Show } from '$lib/types';

	const { summary, description, url, formatted_start }: Show = $props();
</script>

<div class="list_item-show">
	<span class={css({ textStyle: 'h4' })}>
		{#if url?.val}
			<a href={url.val} target="_blank">
				{formatted_start} @ {summary}
			</a>
		{:else}
			<span>
				{formatted_start} @ {summary}
			</span>
		{/if}
	</span>
	<p>{description}</p>
</div>
