// src/pages/music.tsx
import { Layout, Releases } from '@components'
import { Stack } from '@styled-system/jsx'
import { SEO } from 'src/components/Seo'

const IndexPage = () => (
  <Layout>
    <SEO title="Fullbloods Music" />
    <Stack gap="4">
      <h1>Music</h1>
      <Releases />
    </Stack>
  </Layout>
)

export default IndexPage

// src/routes/music/+page.svelte
<script lang="ts">
	import { grid, gridItem, stack } from 'styled-system/patterns';
	import Release from './Release.svelte';
	const { data } = $props();
</script>

<svelte:head>
	<title>Music | Fullbloods</title>
	<meta name="description" content="Musical releases by Fullbloods" />
</svelte:head>

<div class={stack({ gap: 4 })}>
	<h1>Music</h1>

	<div
		class={grid({
			columns: [1, 2, 3],
			gap: [10, 4]
		})}
	>
		{#each data.releases as release (release.slug)}
			<div class={gridItem()}>
				<Release {...release} />
			</div>
		{/each}
	</div>
</div>
