// src/components/Release.tsx
import { Link } from 'gatsby'
import { Box, Stack } from '@styled-system/jsx'
import { format } from 'date-fns'
import { AlbumCover } from './AlbumCover'
import { ListenLinks } from './ListenLinks'
import { IRelease } from '@types'
import { css } from '@styled-system/css'

export function Release(release: IRelease) {
  const { title, release_date, spotify, apm, bandcamp, slug, highdive } =
    release
  return (
    <Stack gap="2">
      <Link to={`/${slug}`}>
        <AlbumCover release={release} />
      </Link>
      <Box>
        <span
          className={css({
            textStyle: 'h5',
          })}
        >
          <Link to={`/${slug}`}>{title}</Link>
        </span>
        <span className={css({ textStyle: 'info' })}>
          {format(new Date(release_date), 'MMMM d, yyyy')}
        </span>
        <ListenLinks
          spotify={spotify}
          apm={apm}
          bandcamp={bandcamp}
          highdive={highdive}
        />
      </Box>
    </Stack>
  )
}

export default IRelease

// src/routes/music/Release.svelte
<script lang="ts">
	import { format } from 'date-fns';
	import { css } from 'styled-system/css';
	import { box, stack } from 'styled-system/patterns';

	import ListenLinks from '$lib/components/ListenLinks.svelte';
	import PictureFrame from '$lib/components/PictureFrame.svelte';
	import type { Release } from '$lib/types';

	const { slug, title, release_date, spotify, apm, bandcamp, highdive, imageData }: Release =
		$props();
</script>

<div class={stack({ gap: 2 })}>
	{#if imageData}
		<a href={`/music/${slug}`} aria-label={`View ${title}`}>
			<PictureFrame>
				<enhanced:img src={imageData.default} alt={`Cover art for ${title}`} />
			</PictureFrame>
		</a>
	{/if}
	<div class={box()}>
		<span
			class={css({
				textStyle: 'h5'
			})}
		>
			<a href={`/music/${slug}`}>{title}</a>
		</span>
		<span class={css({ textStyle: 'info' })}>
			{format(new Date(release_date), 'MMMM d, yyyy')}
		</span>
		<ListenLinks {spotify} {apm} {bandcamp} {highdive} />
	</div>
</div>
